version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sba301_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./docker/init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/entrypoint.sh:/entrypoint.sh
    entrypoint: /bin/bash -c "tr -d '\\r' < /entrypoint.sh > /tmp/entrypoint.sh && bash /tmp/entrypoint.sh"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q "SELECT 1" -b -C || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
    networks:
      - sba301_network
  ngrok:
    image: ngrok/ngrok:latest
    container_name: sba301_ngrok
    restart: always
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - http
      - --url=seamus-monoecious-retractively.ngrok-free.dev
      - host.docker.internal:8080
    ports:
      - "4040:4040"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - sba301_network

volumes:
  sqlserver_data:
    driver: local

networks:
  sba301_network:
    driver: bridge

